spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.32.33:8848,192.168.32.34:8848,192.168.32.35:8848  #.169:8848
        username: nacos
        password: nacos
  data:
      mongodb:
        uri: mongodb://yzl:yzl123@192.168.32.138:27017,192.168.32.139:27017,192.168.32.140:27017/yzl?slaveOk=true&replicaSet=set0&write=1&readPreference=secondaryPreferred&connectTimeoutMS=300000
  datasource:
    yzlverify:
      username: yzl_crm
      password: YZL123456!
      jdbc-url: jdbc:mysql://192.168.32.33:3306/yzl_verify?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      #mysql8版本以上驱动包指定新的驱动类
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 8
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
    master:
      username: yzl_crm
      password: YZL123456!
      jdbc-url: jdbc:mysql://192.168.32.33:3306/yzl_crm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      username: yzl_crm
      password: YZL123456!
      jdbc-url: jdbc:mysql://192.168.32.33:3306/yzl_crm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    cluster:
      nodes: 192.168.32.33:6379,192.168.32.34:6379,192.168.32.35:6379
    password: YZL123456!
    database: 0
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 20
        min-idle: 0
    timeout: 2000
    sentinel:
      master: mymaster
      nodes: 192.168.32.33:26379,192.168.32.34:26379,192.168.32.35:26379